language: generic
os:
  - osx
  - linux
dist: xenial
sudo: false
cache:
  directories:
    - "$HOME/Library/texlive/2016basic/texmf-var/luatex-cache"
    - "$HOME/texlive/2016/texmf-var/luatex-cache"
before_install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
  - chmod +x install-tex.sh tlmgr.sh
install:
  - . ./install-tex.sh
  - sudo /usr/local/texlive/2015/bin/x86_64-darwin/tlmgr path add
  - ./tlmgr.sh update --self --all || echo "ignore errors"
  - ./tlmgr.sh install latexmk collection-luatex collection-langjapanese collection-fontsrecommended filehook type1cm mdframed needspace unicode-math
script:
  - make all
after_success:
  - ./deploy.sh
env:
  global:
    secure: CKg93mds99OKADGnDxtJB2TTT+u8jcEQAW3c82QUa6MNNKXHvK6L5U9eUdgMrJTm+MRAKd6g7unG8ECW63a8q909vlhPU0g2Ssv/1t+OlpK3sJKEvYVuMrFy1GndC60LEktpaHvOj/WCu9ftf2mcvR1s+U73jBMm43HATaimXs4m/uD6fRRb4g6ZXi4zeDj8EQe6BirSrslUczEu+G6dT/+i6S61FOOu/OF1PUieEFqlI5J6wJewOnBU6FpynkJdTet6q44BEvCMLgKG8L1XQ03G13MDAgMea3mimzjz2E7b7SbdTX5FkyjrGS1Rx4unVPh7tYK65MQvwc1qj71zf9ARkaaR/iuuDvG9Isacgxwhvd3HiegbXOd/7wqmSwPqVu8IZBJSW24lEMaVz7OfpwE/eOCEgGbRdY+E43FATqdJH6KpAwd5KyEx6AWmRYvykAPtRzLKmWMJRIupBzGEIrLAmyO9UXJQB4xSSn/fGvOuBRYBrdlcEcfvIad1VGZMRAJE9omseLBuj6x3fbl4y66TkevgA9gD9cikiKcORF2REGFsRW6ny/YfqlPnwOjPSL6q3SZsgxG/cieHQjmHbyzWhmu/s+xiv7Jqr4q+QwYp4pW3+h3t8+yxu4L/M4lsIZsNgSUa86dmC4lDWRbRHEMOdUk7Sc35wXlTx9PZnb8=
